# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-20 19:10
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190420_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(help_text='正文必须为MakeDown格式', verbose_name='正文'),
        ),
    ]
