# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190420_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='正文必须为MakeDown格式', verbose_name='正文'),
        ),
    ]
