# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='image', verbose_name='简介图片'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='image', verbose_name='内容图片'),
        ),
    ]
