# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-03 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190403_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag_filter',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Filter', verbose_name='所属小标签'),
        ),
    ]
