# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-03 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190403_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='tag',
        ),
    ]
