# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-04 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_filter_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
